services:
  - type: web
    name: oracle-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: SUPABASE_URL
        fromDotEnv: true
      - key: SUPABASE_ANON_KEY
        fromDotEnv: true
      # include all others used in .env
