name: CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests + coverage
        run: npm run test:coverage

      - name: Build backend & frontend
        run: npm run build

      - name: Upload coverage to Codecov
        if: success() && steps.test.outcome == 'success'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/*.json
          flags: unittests
