name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'oracle-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger Vercel Deployment
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_<your_vercel_project_id>/12345678?buildCache=false"
