name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Push changes to GitHub, using the PAT for authentication
      - name: Push changes to GitHub
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.SPIRALOGIC_ORACLE_SYSTEM }} # Reference the secret in your workflow
